// <auto-generated />
using System;
using Football.EF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Football.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230916220917_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Football.Core.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FoundingDate")
                        .HasColumnType("date");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Club", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoundingDate = new DateTime(1899, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            Name = "Fc Barcelona"
                        },
                        new
                        {
                            Id = 2,
                            FoundingDate = new DateTime(1902, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            Name = "Real Madrid"
                        });
                });

            modelBuilder.Entity("Football.Core.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("League", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "La Liga"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Premiere League"
                        });
                });

            modelBuilder.Entity("Football.Core.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthYear")
                        .HasColumnType("date");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Player", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = new DateTime(1987, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClubId = 1,
                            Name = "Lioniel Messi",
                            Nation = ""
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = new DateTime(1984, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClubId = 1,
                            Name = "Andres Iniesta",
                            Nation = ""
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = new DateTime(1980, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClubId = 1,
                            Name = "Xavi Hernandez",
                            Nation = ""
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = new DateTime(1985, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClubId = 2,
                            Name = "Cristiano Ronaldo",
                            Nation = ""
                        },
                        new
                        {
                            Id = 5,
                            BirthYear = new DateTime(1987, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClubId = 2,
                            Name = "Karim Benzema",
                            Nation = ""
                        },
                        new
                        {
                            Id = 6,
                            BirthYear = new DateTime(1982, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClubId = 2,
                            Name = "KAKA",
                            Nation = ""
                        });
                });

            modelBuilder.Entity("Football.Core.Models.Club", b =>
                {
                    b.HasOne("Football.Core.Models.League", "League")
                        .WithMany("Clubs")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("League");
                });

            modelBuilder.Entity("Football.Core.Models.Player", b =>
                {
                    b.HasOne("Football.Core.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Football.Core.Models.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Football.Core.Models.League", b =>
                {
                    b.Navigation("Clubs");
                });
#pragma warning restore 612, 618
        }
    }
}
